apiVersion: cert-manager.io/
kind: Certificate 
metadata:
  name: {{ .Release.Name }}-certs
spec:
  secretName: {{ .Release.Name }}-certs
  issuerRef:
    name: letsencrypt-{{ .Release.Name }}
    kind: Issuer
  dnsNames:
  - {{ .Values.host }}
